import{a as S,S as q,i as c}from"./assets/vendor-DnCMJMY2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const P="55699882-78e76ba09440d2b00f4853bc0";async function d(r,t){const{data:o}=await S.get("https://pixabay.com/api/",{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${t}`,per_page:15}});return o}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformaturl:o,largeImageURL:n,tags:e,likes:a,views:i,comments:b,downloads:w})=>`
        <li class="gallery-item">
        <a href="${n}"> 
        <img src="${o}" alt="${e}" />
        </a>
        <p>Likes: ${a}</p>
        <p>Views: ${i}</p>
        <p>Comments: ${b}</p>
        <p>Downloads: ${w}</p>
        </li>
        `).join("");u.insertAdjacentHTML("beforeend",t),$.refresh()}function v(){u.innerHTML=""}function y(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function B(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const M=document.querySelector(".form"),x=document.querySelector(".load-more-btn");let s=1,p="";M.addEventListener("submit",E);x.addEventListener("click",O);async function E(r){r.preventDefault();const t=r.currentTarget.elements["search-text"].value.trim();if(!t){c.warning({message:"Please enter a search query"});return}p=t,s=1,v(),l(),y();try{const{hits:o,totalHits:n}=await d(t,s);o.length>0?(h(o),L(s,n)):c.show({color:"#EF4040",messageColor:"#FAFAFB",message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:"322px"})}catch(o){c.error({message:o.message})}finally{r.target.reset(),g()}}async function O(){s+=1,y(),l();try{const{hits:r,totalHits:t}=await d(p,s);h(r);const o=document.querySelector(".gallery-item");if(o){const n=o.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}L(s,t)}catch(r){c.error({message:r.message})}finally{g()}}function L(r,t){r*15>=t?(l(),c.info({message:"We're sorry, but you've reached the end of search results."})):B()}
//# sourceMappingURL=index.js.map
